module.exports.followerInfo = [
  {
    "login": "lunatech",
    "id": 1460,
    "avatar_url": "https://avatars1.githubusercontent.com/u/1460?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/lunatech",
    "html_url": "https://github.com/lunatech",
    "followers_url": "https://api.github.com/users/lunatech/followers",
    "following_url": "https://api.github.com/users/lunatech/following{/other_user}",
    "gists_url": "https://api.github.com/users/lunatech/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/lunatech/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/lunatech/subscriptions",
    "organizations_url": "https://api.github.com/users/lunatech/orgs",
    "repos_url": "https://api.github.com/users/lunatech/repos",
    "events_url": "https://api.github.com/users/lunatech/events{/privacy}",
    "received_events_url": "https://api.github.com/users/lunatech/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "snucko",
    "id": 1626,
    "avatar_url": "https://avatars2.githubusercontent.com/u/1626?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/snucko",
    "html_url": "https://github.com/snucko",
    "followers_url": "https://api.github.com/users/snucko/followers",
    "following_url": "https://api.github.com/users/snucko/following{/other_user}",
    "gists_url": "https://api.github.com/users/snucko/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/snucko/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/snucko/subscriptions",
    "organizations_url": "https://api.github.com/users/snucko/orgs",
    "repos_url": "https://api.github.com/users/snucko/repos",
    "events_url": "https://api.github.com/users/snucko/events{/privacy}",
    "received_events_url": "https://api.github.com/users/snucko/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "muncman",
    "id": 1702,
    "avatar_url": "https://avatars1.githubusercontent.com/u/1702?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/muncman",
    "html_url": "https://github.com/muncman",
    "followers_url": "https://api.github.com/users/muncman/followers",
    "following_url": "https://api.github.com/users/muncman/following{/other_user}",
    "gists_url": "https://api.github.com/users/muncman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/muncman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/muncman/subscriptions",
    "organizations_url": "https://api.github.com/users/muncman/orgs",
    "repos_url": "https://api.github.com/users/muncman/repos",
    "events_url": "https://api.github.com/users/muncman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/muncman/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "joshua",
    "id": 1718,
    "avatar_url": "https://avatars1.githubusercontent.com/u/1718?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/joshua",
    "html_url": "https://github.com/joshua",
    "followers_url": "https://api.github.com/users/joshua/followers",
    "following_url": "https://api.github.com/users/joshua/following{/other_user}",
    "gists_url": "https://api.github.com/users/joshua/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/joshua/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/joshua/subscriptions",
    "organizations_url": "https://api.github.com/users/joshua/orgs",
    "repos_url": "https://api.github.com/users/joshua/repos",
    "events_url": "https://api.github.com/users/joshua/events{/privacy}",
    "received_events_url": "https://api.github.com/users/joshua/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jameydavis",
    "id": 1781,
    "avatar_url": "https://avatars0.githubusercontent.com/u/1781?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jameydavis",
    "html_url": "https://github.com/jameydavis",
    "followers_url": "https://api.github.com/users/jameydavis/followers",
    "following_url": "https://api.github.com/users/jameydavis/following{/other_user}",
    "gists_url": "https://api.github.com/users/jameydavis/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jameydavis/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jameydavis/subscriptions",
    "organizations_url": "https://api.github.com/users/jameydavis/orgs",
    "repos_url": "https://api.github.com/users/jameydavis/repos",
    "events_url": "https://api.github.com/users/jameydavis/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jameydavis/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "teddyzetterlund",
    "id": 1955,
    "avatar_url": "https://avatars3.githubusercontent.com/u/1955?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/teddyzetterlund",
    "html_url": "https://github.com/teddyzetterlund",
    "followers_url": "https://api.github.com/users/teddyzetterlund/followers",
    "following_url": "https://api.github.com/users/teddyzetterlund/following{/other_user}",
    "gists_url": "https://api.github.com/users/teddyzetterlund/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/teddyzetterlund/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/teddyzetterlund/subscriptions",
    "organizations_url": "https://api.github.com/users/teddyzetterlund/orgs",
    "repos_url": "https://api.github.com/users/teddyzetterlund/repos",
    "events_url": "https://api.github.com/users/teddyzetterlund/events{/privacy}",
    "received_events_url": "https://api.github.com/users/teddyzetterlund/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Pawka",
    "id": 2011,
    "avatar_url": "https://avatars1.githubusercontent.com/u/2011?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Pawka",
    "html_url": "https://github.com/Pawka",
    "followers_url": "https://api.github.com/users/Pawka/followers",
    "following_url": "https://api.github.com/users/Pawka/following{/other_user}",
    "gists_url": "https://api.github.com/users/Pawka/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Pawka/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Pawka/subscriptions",
    "organizations_url": "https://api.github.com/users/Pawka/orgs",
    "repos_url": "https://api.github.com/users/Pawka/repos",
    "events_url": "https://api.github.com/users/Pawka/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Pawka/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kakutani",
    "id": 2160,
    "avatar_url": "https://avatars1.githubusercontent.com/u/2160?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kakutani",
    "html_url": "https://github.com/kakutani",
    "followers_url": "https://api.github.com/users/kakutani/followers",
    "following_url": "https://api.github.com/users/kakutani/following{/other_user}",
    "gists_url": "https://api.github.com/users/kakutani/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kakutani/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kakutani/subscriptions",
    "organizations_url": "https://api.github.com/users/kakutani/orgs",
    "repos_url": "https://api.github.com/users/kakutani/repos",
    "events_url": "https://api.github.com/users/kakutani/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kakutani/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "softprops",
    "id": 2242,
    "avatar_url": "https://avatars3.githubusercontent.com/u/2242?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/softprops",
    "html_url": "https://github.com/softprops",
    "followers_url": "https://api.github.com/users/softprops/followers",
    "following_url": "https://api.github.com/users/softprops/following{/other_user}",
    "gists_url": "https://api.github.com/users/softprops/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/softprops/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/softprops/subscriptions",
    "organizations_url": "https://api.github.com/users/softprops/orgs",
    "repos_url": "https://api.github.com/users/softprops/repos",
    "events_url": "https://api.github.com/users/softprops/events{/privacy}",
    "received_events_url": "https://api.github.com/users/softprops/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jmazzi",
    "id": 2273,
    "avatar_url": "https://avatars1.githubusercontent.com/u/2273?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jmazzi",
    "html_url": "https://github.com/jmazzi",
    "followers_url": "https://api.github.com/users/jmazzi/followers",
    "following_url": "https://api.github.com/users/jmazzi/following{/other_user}",
    "gists_url": "https://api.github.com/users/jmazzi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jmazzi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jmazzi/subscriptions",
    "organizations_url": "https://api.github.com/users/jmazzi/orgs",
    "repos_url": "https://api.github.com/users/jmazzi/repos",
    "events_url": "https://api.github.com/users/jmazzi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jmazzi/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "soulim",
    "id": 2370,
    "avatar_url": "https://avatars1.githubusercontent.com/u/2370?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/soulim",
    "html_url": "https://github.com/soulim",
    "followers_url": "https://api.github.com/users/soulim/followers",
    "following_url": "https://api.github.com/users/soulim/following{/other_user}",
    "gists_url": "https://api.github.com/users/soulim/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/soulim/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/soulim/subscriptions",
    "organizations_url": "https://api.github.com/users/soulim/orgs",
    "repos_url": "https://api.github.com/users/soulim/repos",
    "events_url": "https://api.github.com/users/soulim/events{/privacy}",
    "received_events_url": "https://api.github.com/users/soulim/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "libin",
    "id": 2413,
    "avatar_url": "https://avatars2.githubusercontent.com/u/2413?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/libin",
    "html_url": "https://github.com/libin",
    "followers_url": "https://api.github.com/users/libin/followers",
    "following_url": "https://api.github.com/users/libin/following{/other_user}",
    "gists_url": "https://api.github.com/users/libin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/libin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/libin/subscriptions",
    "organizations_url": "https://api.github.com/users/libin/orgs",
    "repos_url": "https://api.github.com/users/libin/repos",
    "events_url": "https://api.github.com/users/libin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/libin/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "zac",
    "id": 2525,
    "avatar_url": "https://avatars0.githubusercontent.com/u/2525?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zac",
    "html_url": "https://github.com/zac",
    "followers_url": "https://api.github.com/users/zac/followers",
    "following_url": "https://api.github.com/users/zac/following{/other_user}",
    "gists_url": "https://api.github.com/users/zac/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zac/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zac/subscriptions",
    "organizations_url": "https://api.github.com/users/zac/orgs",
    "repos_url": "https://api.github.com/users/zac/repos",
    "events_url": "https://api.github.com/users/zac/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zac/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Aeon",
    "id": 2532,
    "avatar_url": "https://avatars1.githubusercontent.com/u/2532?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Aeon",
    "html_url": "https://github.com/Aeon",
    "followers_url": "https://api.github.com/users/Aeon/followers",
    "following_url": "https://api.github.com/users/Aeon/following{/other_user}",
    "gists_url": "https://api.github.com/users/Aeon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Aeon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Aeon/subscriptions",
    "organizations_url": "https://api.github.com/users/Aeon/orgs",
    "repos_url": "https://api.github.com/users/Aeon/repos",
    "events_url": "https://api.github.com/users/Aeon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Aeon/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "baron",
    "id": 2617,
    "avatar_url": "https://avatars3.githubusercontent.com/u/2617?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/baron",
    "html_url": "https://github.com/baron",
    "followers_url": "https://api.github.com/users/baron/followers",
    "following_url": "https://api.github.com/users/baron/following{/other_user}",
    "gists_url": "https://api.github.com/users/baron/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/baron/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/baron/subscriptions",
    "organizations_url": "https://api.github.com/users/baron/orgs",
    "repos_url": "https://api.github.com/users/baron/repos",
    "events_url": "https://api.github.com/users/baron/events{/privacy}",
    "received_events_url": "https://api.github.com/users/baron/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "dennmart",
    "id": 2877,
    "avatar_url": "https://avatars3.githubusercontent.com/u/2877?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dennmart",
    "html_url": "https://github.com/dennmart",
    "followers_url": "https://api.github.com/users/dennmart/followers",
    "following_url": "https://api.github.com/users/dennmart/following{/other_user}",
    "gists_url": "https://api.github.com/users/dennmart/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dennmart/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dennmart/subscriptions",
    "organizations_url": "https://api.github.com/users/dennmart/orgs",
    "repos_url": "https://api.github.com/users/dennmart/repos",
    "events_url": "https://api.github.com/users/dennmart/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dennmart/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "bjtitus",
    "id": 3250,
    "avatar_url": "https://avatars0.githubusercontent.com/u/3250?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bjtitus",
    "html_url": "https://github.com/bjtitus",
    "followers_url": "https://api.github.com/users/bjtitus/followers",
    "following_url": "https://api.github.com/users/bjtitus/following{/other_user}",
    "gists_url": "https://api.github.com/users/bjtitus/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bjtitus/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bjtitus/subscriptions",
    "organizations_url": "https://api.github.com/users/bjtitus/orgs",
    "repos_url": "https://api.github.com/users/bjtitus/repos",
    "events_url": "https://api.github.com/users/bjtitus/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bjtitus/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "nextmat",
    "id": 3279,
    "avatar_url": "https://avatars2.githubusercontent.com/u/3279?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nextmat",
    "html_url": "https://github.com/nextmat",
    "followers_url": "https://api.github.com/users/nextmat/followers",
    "following_url": "https://api.github.com/users/nextmat/following{/other_user}",
    "gists_url": "https://api.github.com/users/nextmat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nextmat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nextmat/subscriptions",
    "organizations_url": "https://api.github.com/users/nextmat/orgs",
    "repos_url": "https://api.github.com/users/nextmat/repos",
    "events_url": "https://api.github.com/users/nextmat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nextmat/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mizzy",
    "id": 3620,
    "avatar_url": "https://avatars3.githubusercontent.com/u/3620?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mizzy",
    "html_url": "https://github.com/mizzy",
    "followers_url": "https://api.github.com/users/mizzy/followers",
    "following_url": "https://api.github.com/users/mizzy/following{/other_user}",
    "gists_url": "https://api.github.com/users/mizzy/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mizzy/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mizzy/subscriptions",
    "organizations_url": "https://api.github.com/users/mizzy/orgs",
    "repos_url": "https://api.github.com/users/mizzy/repos",
    "events_url": "https://api.github.com/users/mizzy/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mizzy/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ubuntufreak",
    "id": 3849,
    "avatar_url": "https://avatars2.githubusercontent.com/u/3849?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ubuntufreak",
    "html_url": "https://github.com/ubuntufreak",
    "followers_url": "https://api.github.com/users/ubuntufreak/followers",
    "following_url": "https://api.github.com/users/ubuntufreak/following{/other_user}",
    "gists_url": "https://api.github.com/users/ubuntufreak/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ubuntufreak/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ubuntufreak/subscriptions",
    "organizations_url": "https://api.github.com/users/ubuntufreak/orgs",
    "repos_url": "https://api.github.com/users/ubuntufreak/repos",
    "events_url": "https://api.github.com/users/ubuntufreak/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ubuntufreak/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "justinabrahms",
    "id": 3853,
    "avatar_url": "https://avatars2.githubusercontent.com/u/3853?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/justinabrahms",
    "html_url": "https://github.com/justinabrahms",
    "followers_url": "https://api.github.com/users/justinabrahms/followers",
    "following_url": "https://api.github.com/users/justinabrahms/following{/other_user}",
    "gists_url": "https://api.github.com/users/justinabrahms/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/justinabrahms/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/justinabrahms/subscriptions",
    "organizations_url": "https://api.github.com/users/justinabrahms/orgs",
    "repos_url": "https://api.github.com/users/justinabrahms/repos",
    "events_url": "https://api.github.com/users/justinabrahms/events{/privacy}",
    "received_events_url": "https://api.github.com/users/justinabrahms/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "dayne",
    "id": 3921,
    "avatar_url": "https://avatars2.githubusercontent.com/u/3921?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dayne",
    "html_url": "https://github.com/dayne",
    "followers_url": "https://api.github.com/users/dayne/followers",
    "following_url": "https://api.github.com/users/dayne/following{/other_user}",
    "gists_url": "https://api.github.com/users/dayne/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dayne/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dayne/subscriptions",
    "organizations_url": "https://api.github.com/users/dayne/orgs",
    "repos_url": "https://api.github.com/users/dayne/repos",
    "events_url": "https://api.github.com/users/dayne/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dayne/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "chrisledet",
    "id": 4164,
    "avatar_url": "https://avatars2.githubusercontent.com/u/4164?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/chrisledet",
    "html_url": "https://github.com/chrisledet",
    "followers_url": "https://api.github.com/users/chrisledet/followers",
    "following_url": "https://api.github.com/users/chrisledet/following{/other_user}",
    "gists_url": "https://api.github.com/users/chrisledet/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/chrisledet/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/chrisledet/subscriptions",
    "organizations_url": "https://api.github.com/users/chrisledet/orgs",
    "repos_url": "https://api.github.com/users/chrisledet/repos",
    "events_url": "https://api.github.com/users/chrisledet/events{/privacy}",
    "received_events_url": "https://api.github.com/users/chrisledet/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "aitor",
    "id": 4295,
    "avatar_url": "https://avatars2.githubusercontent.com/u/4295?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aitor",
    "html_url": "https://github.com/aitor",
    "followers_url": "https://api.github.com/users/aitor/followers",
    "following_url": "https://api.github.com/users/aitor/following{/other_user}",
    "gists_url": "https://api.github.com/users/aitor/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aitor/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aitor/subscriptions",
    "organizations_url": "https://api.github.com/users/aitor/orgs",
    "repos_url": "https://api.github.com/users/aitor/repos",
    "events_url": "https://api.github.com/users/aitor/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aitor/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "dhou",
    "id": 4307,
    "avatar_url": "https://avatars2.githubusercontent.com/u/4307?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dhou",
    "html_url": "https://github.com/dhou",
    "followers_url": "https://api.github.com/users/dhou/followers",
    "following_url": "https://api.github.com/users/dhou/following{/other_user}",
    "gists_url": "https://api.github.com/users/dhou/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dhou/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dhou/subscriptions",
    "organizations_url": "https://api.github.com/users/dhou/orgs",
    "repos_url": "https://api.github.com/users/dhou/repos",
    "events_url": "https://api.github.com/users/dhou/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dhou/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "oliyoung",
    "id": 4388,
    "avatar_url": "https://avatars2.githubusercontent.com/u/4388?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/oliyoung",
    "html_url": "https://github.com/oliyoung",
    "followers_url": "https://api.github.com/users/oliyoung/followers",
    "following_url": "https://api.github.com/users/oliyoung/following{/other_user}",
    "gists_url": "https://api.github.com/users/oliyoung/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/oliyoung/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/oliyoung/subscriptions",
    "organizations_url": "https://api.github.com/users/oliyoung/orgs",
    "repos_url": "https://api.github.com/users/oliyoung/repos",
    "events_url": "https://api.github.com/users/oliyoung/events{/privacy}",
    "received_events_url": "https://api.github.com/users/oliyoung/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ascarter",
    "id": 4931,
    "avatar_url": "https://avatars2.githubusercontent.com/u/4931?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ascarter",
    "html_url": "https://github.com/ascarter",
    "followers_url": "https://api.github.com/users/ascarter/followers",
    "following_url": "https://api.github.com/users/ascarter/following{/other_user}",
    "gists_url": "https://api.github.com/users/ascarter/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ascarter/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ascarter/subscriptions",
    "organizations_url": "https://api.github.com/users/ascarter/orgs",
    "repos_url": "https://api.github.com/users/ascarter/repos",
    "events_url": "https://api.github.com/users/ascarter/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ascarter/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "digicyc",
    "id": 5057,
    "avatar_url": "https://avatars2.githubusercontent.com/u/5057?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/digicyc",
    "html_url": "https://github.com/digicyc",
    "followers_url": "https://api.github.com/users/digicyc/followers",
    "following_url": "https://api.github.com/users/digicyc/following{/other_user}",
    "gists_url": "https://api.github.com/users/digicyc/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/digicyc/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/digicyc/subscriptions",
    "organizations_url": "https://api.github.com/users/digicyc/orgs",
    "repos_url": "https://api.github.com/users/digicyc/repos",
    "events_url": "https://api.github.com/users/digicyc/events{/privacy}",
    "received_events_url": "https://api.github.com/users/digicyc/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "juanghurtado",
    "id": 5070,
    "avatar_url": "https://avatars1.githubusercontent.com/u/5070?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/juanghurtado",
    "html_url": "https://github.com/juanghurtado",
    "followers_url": "https://api.github.com/users/juanghurtado/followers",
    "following_url": "https://api.github.com/users/juanghurtado/following{/other_user}",
    "gists_url": "https://api.github.com/users/juanghurtado/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/juanghurtado/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/juanghurtado/subscriptions",
    "organizations_url": "https://api.github.com/users/juanghurtado/orgs",
    "repos_url": "https://api.github.com/users/juanghurtado/repos",
    "events_url": "https://api.github.com/users/juanghurtado/events{/privacy}",
    "received_events_url": "https://api.github.com/users/juanghurtado/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "assimovt",
    "id": 5113,
    "avatar_url": "https://avatars0.githubusercontent.com/u/5113?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/assimovt",
    "html_url": "https://github.com/assimovt",
    "followers_url": "https://api.github.com/users/assimovt/followers",
    "following_url": "https://api.github.com/users/assimovt/following{/other_user}",
    "gists_url": "https://api.github.com/users/assimovt/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/assimovt/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/assimovt/subscriptions",
    "organizations_url": "https://api.github.com/users/assimovt/orgs",
    "repos_url": "https://api.github.com/users/assimovt/repos",
    "events_url": "https://api.github.com/users/assimovt/events{/privacy}",
    "received_events_url": "https://api.github.com/users/assimovt/received_events",
    "type": "User",
    "site_admin": false
  }
]