module.exports.user =  {
    "login": "plasticbugs",
    "id": 229260,
    "avatar_url": "https://avatars3.githubusercontent.com/u/229260?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/plasticbugs",
    "html_url": "https://github.com/plasticbugs",
    "followers_url": "https://api.github.com/users/plasticbugs/followers",
    "following_url": "https://api.github.com/users/plasticbugs/following{/other_user}",
    "gists_url": "https://api.github.com/users/plasticbugs/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/plasticbugs/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/plasticbugs/subscriptions",
    "organizations_url": "https://api.github.com/users/plasticbugs/orgs",
    "repos_url": "https://api.github.com/users/plasticbugs/repos",
    "events_url": "https://api.github.com/users/plasticbugs/events{/privacy}",
    "received_events_url": "https://api.github.com/users/plasticbugs/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Scott Moschella",
    "company": null,
    "blog": "",
    "location": "San Francisco, CA",
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 20,
    "public_gists": 3,
    "followers": 4,
    "following": 2,
    "created_at": "2010-03-24T07:21:12Z",
    "updated_at": "2017-08-18T14:19:52Z",
    "private_gists": 10,
    "total_private_repos": 28,
    "owned_private_repos": 0,
    "disk_usage": 5944,
    "collaborators": 0,
    "two_factor_authentication": true,
    "plan": {
      "name": "free",
      "space": 976562499,
      "collaborators": 0,
      "private_repos": 0
    }
  }
